"""initial v1 schema

Revision ID: 1b9d75d25200
Revises: 
Create Date: 2026-09-17 23:12:56.204010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.user
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1b9d75d25200'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('tasks',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('user_id', app.models.user.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='task_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(title) > 0', name='ck_tasks_title_non_empty'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('ix_tasks_updated_at', 'tasks', ['updated_at'], unique=False)
    op.create_index('ix_tasks_user_id', 'tasks', ['user_id'], unique=False)
    op.create_index('ix_tasks_user_status', 'tasks', ['user_id', 'status'], unique=False)
    op.create_table('time_sessions',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('user_id', app.models.user.GUID(), nullable=False),
    sa.Column('task_id', app.models.user.GUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duration IS NULL OR duration >= 0', name='ck_time_sessions_duration_non_negative'),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name='ck_time_sessions_ended_after_start'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_time_sessions_ended_at', 'time_sessions', ['ended_at'], unique=False)
    op.create_index('ix_time_sessions_started_at', 'time_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_time_sessions_task_id'), 'time_sessions', ['task_id'], unique=False)
    op.create_index('ix_time_sessions_user_id', 'time_sessions', ['user_id'], unique=False)
    op.create_index('ix_time_sessions_user_task', 'time_sessions', ['user_id', 'task_id'], unique=False)
    # Partial unique index to enforce one active timer per user (where ended_at IS NULL)
    # Works for both PostgreSQL and SQLite (both support partial indexes)
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_time_sessions_one_active_per_user ON time_sessions (user_id) WHERE ended_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_time_sessions_one_active_per_user")
    op.drop_index('ix_time_sessions_user_task', table_name='time_sessions')
    op.drop_index('ix_time_sessions_user_id', table_name='time_sessions')
    op.drop_index(op.f('ix_time_sessions_task_id'), table_name='time_sessions')
    op.drop_index('ix_time_sessions_started_at', table_name='time_sessions')
    op.drop_index('ix_time_sessions_ended_at', table_name='time_sessions')
    op.drop_table('time_sessions')
    op.drop_index('ix_tasks_user_status', table_name='tasks')
    op.drop_index('ix_tasks_user_id', table_name='tasks')
    op.drop_index('ix_tasks_updated_at', table_name='tasks')
    op.drop_index('ix_tasks_created_at', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
